project:
  type: website

website:
  title: "Global-Babies"
  navbar:
    left:
      - href: index.qmd
        text: Overview
      - people.qmd
      - thesample.qmd
      - dataproducts.qmd
      - protocol.qmd
      - qa.md
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

