project:
  type: website
  output-dir: docs

website:
  favicon: "pics/BABIES-logo.png"
  title: "Global Babies"
  navbar:
    logo: "pics/BABIES-logo.png"
    left:
      - href: index.qmd
        text: Overview
      - people.qmd
      - thesample.qmd
      - dataproducts.qmd
      - protocol.qmd
      - quality.qmd
      - text: Links
        menu:
        - href: https://databrary.org
          text: "![](pics/databrary-nav.png)"
        - href: https://datavyu.org
          text: "![](pics/datavyu-nav.png)"
      
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

resources:
  - CNAME
